# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 559)
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget#centralwidget { border-image: url(:/newPrefix/binance-ra-mat-pancake-swap-mini.png) 0 0 0 0 stretch stretch ;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LD_addressA = QtWidgets.QLineEdit(self.centralwidget)
        self.LD_addressA.setGeometry(QtCore.QRect(140, 69, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LD_addressA.setFont(font)
        self.LD_addressA.setObjectName("LD_addressA")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.LD_soluong1 = QtWidgets.QLineEdit(self.centralwidget)
        self.LD_soluong1.setGeometry(QtCore.QRect(440, 69, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LD_soluong1.setFont(font)
        self.LD_soluong1.setObjectName("LD_soluong1")
        self.Btn_Swap = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_Swap.setGeometry(QtCore.QRect(460, 220, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_Swap.setFont(font)
        self.Btn_Swap.setAutoFillBackground(False)
        self.Btn_Swap.setStyleSheet("QPushButton#Btn_Swap { background-color : rgb(204, 102, 0);\n"
"color: Yellow;\n"
"}")
        self.Btn_Swap.setCheckable(False)
        self.Btn_Swap.setObjectName("Btn_Swap")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(120, 370, 631, 141))
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.LD_soluong1_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.LD_soluong1_2.setGeometry(QtCore.QRect(440, 140, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LD_soluong1_2.setFont(font)
        self.LD_soluong1_2.setObjectName("LD_soluong1_2")
        self.LD_addressA_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.LD_addressA_2.setGeometry(QtCore.QRect(140, 140, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LD_addressA_2.setFont(font)
        self.LD_addressA_2.setObjectName("LD_addressA_2")
        self.label_2.raise_()
        self.LD_soluong1.raise_()
        self.LD_addressA.raise_()
        self.label.raise_()
        self.Btn_Swap.raise_()
        self.textEdit.raise_()
        self.LD_soluong1_2.raise_()
        self.LD_addressA_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.LD_addressA.setText(_translate("MainWindow", "      Adress token "))
        self.label_2.setText(_translate("MainWindow", "Token B :"))
        self.LD_soluong1.setText(_translate("MainWindow", "00000"))
        self.Btn_Swap.setText(_translate("MainWindow", "Swap"))
        self.label.setText(_translate("MainWindow", "Token A :"))
        self.LD_soluong1_2.setText(_translate("MainWindow", "00000"))
        self.LD_addressA_2.setText(_translate("MainWindow", "      Adress token "))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
